# Generated by Django 3.2 on 2021-10-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products_id',
            new_name='category_id',
        ),
    ]
